[build]
  command = "npm run build && npm run serve"
  publish="dist"
  base = "frontend"

[[redirects]]
  force = true
  from = "/*"
  status = 200

[functions]
  external_node_modules = ["express", "compression", "lightningcss", "esbuild"]
  node_bundler = "esbuild" 