[build]
  command = "npm run generate"
  publish="dist"
  base = "frontend"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  
[functions]
  external_node_modules = ["express", "compression", "lightningcss", "esbuild"]
  node_bundler = "esbuild" 
  included_files = ["../../dist/**"]
