apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - brigadasos-db-prod.yaml
  - ../../base
namespace: nadedb
images:
  - name: brigadasos-db
    newName: ghcr.io/brigadasos/brigadasos-db
    newTag: v0.9.0-1