apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - brigadasos-db-prod.yaml
  - pgroonga.yaml
  - pgsync.yaml
#  - ../../base
namespace: nadedb
images:
  - name: nadedb
    newName: ghcr.io/brigadasos/nadedb
    newTag: v0.9.0-1