kind: PersistentVolume
apiVersion: v1
metadata:
  name: brigadasos-db-pv
  labels:
    type: local
    app: brigadasos-db
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/nvme01/nadedb/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: brigadasos-db-pv-claim
  labels:
    app: brigadasos-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brigadasos-db
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: brigadasos-db
  template:
    metadata:
      labels:
        app: brigadasos-db
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: brigadasos-db
          name: brigadasos-db
          envFrom:
            - configMapRef:
                name: brigadasos-db-config
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /data/
              name: brigadasos-db-vol
      volumes:
        - name: brigadasos-db-vol
          persistentVolumeClaim:
            claimName: brigadasos-db-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: brigadasos-db-service
  labels:
    app: brigadasos-db
spec:
  selector:
    app: brigadasos-db
  ports:
   - port: 5000