apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pgroonga.yaml
- brigadasos-db.yaml
- pgsync.yaml
namespace: nadedb
images:
- name: brigadasos-db
  newName: ghcr.io/brigadasos/brigadasos-db
  newTag: v0.5.5
