apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pgroonga.yaml
namespace: nadedb
images:
- name: nadedb-backend
  newName: ghcr.io/brigadasos/nadedb-backend
  newTag: v0.1.0
